### PR TITLE
feat: support wasm

### PR DESCRIPTION
**Pull request by utamori**
Thanks for the useful templates and articles.

I tried to make this project executable in wasm

Reference
- https://docs.flutter.dev/platform-integration/web/wasm
- https://zenn.dev/tsuruo/articles/6a1d29caa43974

### CODE REVIEW

**Comment by htsuruo** [comment]
@utamori 

Thank you for your request.

Did you check the launch.json file? 
I tried to execute` wasm:flutter-admin-dashboard-template` in launch.json, but the following error occurred:

>Could not find an option named "wasm".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

The reason for the error is likely due to flutter run being unavailable for WebAssembly. 
Additionally, in my opinion, the flutter build command should not be used in launch.json as it is intended for a debug configuration file.

Therefore, could you please remove the WebAssembly configuration from launch.json?
The index.html file seems to be fine.

**Comment by htsuruo** [comment]
Can you see your `flutter doctor` ?
The latest Flutter stable 3.22 doesn't still support `flutter run --wasm`.

**Comment by utamori** [comment]
Sorry for the lack of explanation. 
The --wasm option has been available since version 3.23.0.

> Channel beta, 3.23.0-0.1.pre
```
flutter run -h
    --wasm                                                   Compile to WebAssembly rather than JavaScript.
                                                             See https://flutter.dev/wasm for more
                                                             information.
```

**Comment by htsuruo** [comment]
@utamori 

LGTM👌
Thank you for contribution.

**Pull request merged**
